# Generated by Django 2.2.3 on 2019-07-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_delete_ideia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='senha',
            field=models.CharField(default='SOME STRING', max_length=255, verbose_name='Senha'),
        ),
    ]
